plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.0'
    id 'io.spring.dependency-management' version '1.1.7'
    id "org.openapi.generator" version "7.3.0"
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

openApiGenerate {
    generatorName = "spring"
    inputSpec = "$projectDir/src/main/resources/openapi/openapi.yml"
    outputDir = "$buildDir/generated"
    apiPackage = "com.example.api"
    modelPackage = "com.example.model"
    configOptions = [
            useResponseEntity: "false",
            interfaceOnly: "true",
            useSpringBoot3: "true",
            useTags: "true",
            openApiNullable: "false",
            dateLibrary: "java8",
            hideGenerationTimestamp: "true",
            serializationLibrary: "jackson",
            skipDefaultInterface: "true",
    ]
}

sourceSets {
    main {
        java {
            srcDirs += "$buildDir/generated/src/main/java"
        }
    }
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.1.0'
    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    compileOnly 'org.projectlombok:lombok'
    runtimeOnly 'org.postgresql:postgresql'

    implementation 'org.flywaydb:flyway-core'
    runtimeOnly 'org.flywaydb:flyway-database-postgresql'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    implementation 'org.openapitools:jackson-databind-nullable:0.2.6'
    implementation 'jakarta.validation:jakarta.validation-api'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.yaml:snakeyaml:2.2'

    implementation 'org.mapstruct:mapstruct:1.5.5.Final'

    implementation 'net.coobird:thumbnailator:0.4.21'

    annotationProcessor 'org.projectlombok:lombok',
            'org.mapstruct:mapstruct-processor:1.5.5.Final',
            'org.projectlombok:lombok-mapstruct-binding:0.2.0'

    constraints {
        implementation('org.yaml:snakeyaml') {
            version { strictly '2.2' }
        }
    }

    implementation 'com.fasterxml.jackson.core:jackson-annotations'
    implementation 'com.fasterxml.jackson.core:jackson-databind'

    implementation "org.springframework.boot:spring-boot-starter-oauth2-authorization-server"
    implementation "org.springframework.security:spring-security-oauth2-authorization-server:1.5.6"
}

tasks.named('test') {
    useJUnitPlatform()
}

tasks.withType(JavaCompile) {
    options.compilerArgs = [
            '-Amapstruct.suppressGeneratorTimestamp=true',
            '-Amapstruct.defaultComponentModel=spring'
    ]
}

compileJava.dependsOn tasks.openApiGenerate