CREATE TABLE IF NOT EXISTS outstanding_people (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(20) NOT NULL,
    surname VARCHAR(30) NOT NULL,
    patronymic VARCHAR(50) NOT NULL,
    gender VARCHAR(20) DEFAULT 'NOT_SELECTED' CHECK (gender IN ('NOT_SELECTED', 'MALE', 'FEMALE')),
    year_of_birth INTEGER,
    year_of_death INTEGER,
    photo_url VARCHAR(100),
    biography TEXT,
    is_deleted BOOLEAN DEFAULT FALSE,
    id_academic_titles BIGINT,
    id_academic_degrees BIGINT,
    id_education_subject BIGINT,

    CONSTRAINT fk_outstanding_people_academic_titles
        FOREIGN KEY (id_academic_titles) REFERENCES academic_titles(id) ON DELETE SET NULL,
    CONSTRAINT fk_outstanding_people_academic_degrees
        FOREIGN KEY (id_academic_degrees) REFERENCES academic_degrees(id) ON DELETE SET NULL,
    CONSTRAINT fk_outstanding_people_education_subject
        FOREIGN KEY (id_education_subject) REFERENCES education_subject(id) ON DELETE SET NULL,
    CONSTRAINT chk_year_of_death CHECK (year_of_death >= year_of_birth OR year_of_death IS NULL)
);