CREATE TABLE IF NOT EXISTS achievements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    year INTEGER NOT NULL,
    description TEXT,
    is_deleted BOOLEAN DEFAULT FALSE,
    id_person BIGINT NOT NULL,

    CONSTRAINT fk_achievements_person
        FOREIGN KEY (id_person) REFERENCES outstanding_people(id) ON DELETE CASCADE
);