CREATE TABLE IF NOT EXISTS person_job (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_year INTEGER,
    end_year INTEGER,
    is_current BOOLEAN DEFAULT FALSE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    id_person BIGINT NOT NULL,
    id_job_title BIGINT NOT NULL,

    CONSTRAINT fk_person_job_person
        FOREIGN KEY (id_person) REFERENCES outstanding_people(id) ON DELETE CASCADE,
    CONSTRAINT fk_person_job_job_title
        FOREIGN KEY (id_job_title) REFERENCES job_title(id) ON DELETE RESTRICT,
    CONSTRAINT chk_person_job_years CHECK (
        (end_year IS NULL AND is_current = TRUE) OR
        (end_year >= start_year AND is_current = FALSE) OR
        (start_year IS NULL))
);